package lib.core.enums;

public enum UserAction {
    USER_REGISTERED,
    USER_VERIFIED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_PASSWORD_RESET,
    USER_DELETED,
    USER_UPDATED,
    USER_EMAIL_VERIFIED,
    USER_PASSWORD_CHANGED,
}
